####################################################################
#                                                                  #
# __   ___               _                 _                       #
# \ \ / / |             | |               (_)                      #
#  \ V /| |__   _____  _| |     ___   __ _ _ _ __                  #
#   > < | '_ \ / _ \ \/ / |    / _ \ / _` | | '_ \                 #
#  / . \| |_) | (_) >  <| |___| (_) | (_| | | | | |                #
# /_/ \_\_.__/ \___/_/\_\______\___/ \__, |_|_| |_|                #
#                                     __/ |                        #
#                                    |___/                         #
# If you messed up with the config, just delete it.                #
#           And it"ll generate a new one :)                        #
####################################################################
# - add \n for a new line. Color codes are also support!           #
####################################################################

KickMessage: You are not signed in into Xbox Live!\nSign in, and join back again!
